---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by norguhtar.
--- DateTime: 26.02.19 14:59
---
local inspect = require('inspect')

local config = require("config")

local db = require("db"):new{config = config}


--print(inspect(db))
--print(inspect(db:connect()))

local res = db:query("SELECT * FROM opt.generator")

print(inspect(res))