---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by norguhtar.
--- DateTime: 23.01.19 15:52
---

local inspect=require('inspect')
local field = {
    primary_key = false
}

local function escape_string(value)
   return value:gsub("['\\]", {["'"] = "''", ["\\"] = "\\\\"})
end

function field:new(obj)
    obj = obj or {}

    setmetatable(obj, self)
    self.__index = self
    return obj
end

function field:getForeignKeyJSON()
    if self.type == 'foreign_key' then
        if string.len(self.table)> 0 then

        end
    else
        return ''
    end
end

function field:getValue(value)
    if not value then
        return 'NULL'
    end
    if self.type == 'string' then
        local str_value = escape_string(value)
        if string.len(str_value)>0 then
            return string.format("'%s'", str_value)
        end
    elseif self.type == 'number' then
        local int_value = tonumber(value)
        if int_value then
            return value
        end
    elseif self.type == 'boolean' then
        local bool_value
        if type(value) == 'boolean' then
            bool_value = tostring(value)
        elseif type(value) == 'string' then
            if string.lower(value) == 'true' or value == '1' then
                bool_value = 'TRUE'
            else
                bool_value = 'FALSE'
            end
        elseif type(value) == 'number' then
            if value then
                bool_value = 'TRUE'
            else
                bool_value = 'FALSE'
            end
        end
        return string.format("'%s'", bool_value)
    end

end

function field:getFilter(value)
    if not value then
        return ''
    end
    return string.format("%s=%s", self.name,  self:getValue(value))
end

return field