---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by norguhtar.
--- DateTime: 04.10.2019 17:55
---
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by norguhtar.
--- DateTime: 26.02.19 15:04
---


local _M = {}

function _M:new(obj)
    obj = obj or {}

    if obj.db then
        self.db = obj.db
    end

    setmetatable(obj, self)
    self.__index = self
    return obj
end

function _M:query(sql)
    local db = self.db
    local res = db.query(sql)
    if next(res) then
        return res
    end
end

return _M