---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by norguhtar.
--- DateTime: 26.02.19 15:05
---

local mysql,_ = require("luasql.mysql")

if mysql then
    return mysql
else
    return nil
end