---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by norguhtar.
--- DateTime: 16.09.2019 15:45
---

local err, pg = pcall(require,"pg")

local _M = {}

function _M:new(obj)
    obj = obj or {}

    if not err then
        return nil
    end

    local config = obj.config
    if config then
        self.db = pg.connect({
            host = config.host,
            port = config.port,
            db = config.database,
            user = config.username,
            password = config.password
        })
    end

    setmetatable(obj, self)
    self.__index = self
    return obj
end


function _M:connect()
    local db = self.db

    if db then
        return db
    end
end

local function validate(val)
    if val ~= 'NULL' then
        val = tostring(val)
    end
    if type(val) == 'string' then
        val = "'" .. val .. "'"
    end
    return val:gsub("['\\]", {["'"] = "''", ["\\"] = "\\\\"})
end


function _M:query(sql, ...)
    local db = self.db
    local params = {}
    if {...} then
        for key,val in pairs(...) do
            params[key] = validate(val)
        end
    end

    local query
    if #params then
        query = sql:gsub("?", "%%s")
        query = query:format(unpack(params))
    end

    if db:ping() then
        local res = db:execute(query)
        if next(res) then
            return res[1]
        end
    end
end

function _M:disconnect()
    local db = self.db
    db:close()
end


return _M