---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by norguhtar.
--- DateTime: 26.02.19 13:02
---

local pg = require("data-mapper.db.pg")

local db = {}

local drivers = {
    ["tarantool-pg"] = pg
}

function db:new(obj)
    obj = obj or {}

    local config = obj.config
    if drivers[config.driver] then
        return drivers[config.driver]:new(obj)
    else
        return nil
    end
end

return db
