---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by norguhtar.
--- DateTime: 26.02.19 13:02
---

local postgres = require('data-mapper.db.postgres')
local mysql = require('data-mapper.db.mysql')
local pg = require("data-mapper.db.pg")

local db = {}

function db:new(obj)
    obj = obj or {}

    local config = obj.config
    if config.driver == "postgres" then
        if postgres then
            return postgres:new(obj)
        end
        if pg then
            return pg:new(obj)
        end
    elseif config.driver == "mysql" then
        if mysql then
            return mysql:new(obj)
        end
    end

    setmetatable(obj, self)
    self.__index = self
    return obj
end

return db