---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by norguhtar.
--- DateTime: 02.04.19 13:46
---

local relation = require('data-mapper.relation')
local field = require('data-mapper.field')
local entity = require('data-mapper.entity')
local db = require('data-mapper.db')

-- dependency for later usage
local status = pcall(require, "fun")
if not status then
    error("module fun not found try installing it: luarocks install fun")
end

local dm = {
    db = db,
    relation = relation,
    field = field,
    entity = entity
}

return dm
