---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by norguhtar.
--- DateTime: 02.04.19 13:46
---

local relation = require('relation')
local field = require('field')
local entity = require('entity')
local db = require('db')

local dm = {
    db = db,
    relation = relation,
    field = field,
    entity = entity
}

return dm
