---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by norguhtar.
--- DateTime: 02.04.19 13:46
---

local reation = require('relation')
local field = require('field')
local entity = require('entity')

local dm = {
    reation = reation,
    field = field,
    entity = entity
}

return dm
